name: jkamizato
recipe: drupal9
config:
  webroot: docroot
services:
  appserver:
    type: php:7.3
    overrides:
      environment:
        DRUSH_OPTIONS_URI: https://jkamizato.lndo.site
  node:
    type: node
    globals:
      gulp-cli: latest
      npm: latest
      yarn: latest
    overrides:
      ports:
        - '3000:3000'
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
