name: jkamizato
recipe: drupal9
config:
  webroot: docroot
services:
  appserver:
    type: php:7.3
    overrides:
      environment:
        DRUSH_OPTIONS_URI: https://jkamizato.lndo.site
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
